name: Deploy staging to s3
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps: 
      - name: Setup node
        uses: actions/setup-node@v1
        with: 
            node-version: '10.x'
      - uses: actions/checkout@master
      - name: Deploy to s3
        env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync "advisory opinions" "s3://staging-phila-gov-website-s3/ethicsboard/advisory opinions/" --delete 
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTROBUTION_ID }} --paths "/*"

